### ISSUE TITLE
"Works in Progress" directory

### ISSUE THREAD

**Issue by deckar01** [XioNYC/StarRaiders#16]
**Issue:**
- I was able to complete a page before my request to reserve it in the `Works in Progress` directory was accepted. #15
- When I saw 0 open issues I wondered if there were only 70 pages and the project was complete.
- The page numbering on the archive's document viewer was not immediately obvious.

**Proposed solution:**
- Create an issue for each of the remaining pages.
- Direct contributors to reserve them with a comment.
- Provide a direct link to each page. Example: [Link to page 71](https://archive.org/stream/AtariStarRaidersSourceCode/Atari_Star_Raiders_Source_Code#page/n70/mode/1up)

**Comment by mattcodez** [comment]
Yea I'm not sure the Works in Progress directory has much point if you don't have push permissions to the repository. You can just keep working on your own fork until the PR.

**Comment by XioNYC** [comment]
Fair point.  Hadn't thought of that situation.  Most people fork the project and notify that they're ready for a pull; I "OK" the work and then add the person to the "collaborators" list.  Don't know if that's the "right" way or not.

**Comment by deckar01** [comment]
Closing in response to https://github.com/XioNYC/StarRaiders/issues/18#issuecomment-154767663
