### ISSUE TITLE
Blank Pages

### ISSUE THREAD

**Issue by XioNYC** [XioNYC/StarRaiders#5]
Confirm there's no code on pages 6 and 9

**Comment by jzatarski** [comment]
I believe this is the case, yes, no code on 6 or 9. You'll notice on the previous pages (5 and 8) that the code kind of reaches the end of a section, and also just so happens to end on the very last line of the page (in both cases with a single semicolon on a line by itself). Most likely, the authors put in a .PAGE directive here which, coinciding with the previous page just happening to end before the directive, resulted in an entirely blank page printed out. The original source near the blank pages, in both cases, was likely:

```
;
.PAGE
;
```

**Comment by XioNYC** [comment]
I assumed that there was an explicit page break in the source.  I'm reluctant to add .PAGE directives where they most likely appeared in the source code, though.
