### ISSUE TITLE
008: Unidentified mark

### ISSUE THREAD

**Issue by XioNYC** [XioNYC/StarRaiders#6]
Between lines $D013 and $D400 (TRIG3 and ANTIC)
Seems to be comment "line"; is there gunk on the page?

**Comment by jzatarski** [comment]
while we can't be sure, I think any character that produced a mark like that gunk before the semicolon would not have allowed the file to compile, as it's neither a valid label, a directive, nor assembly instruction of any kind. Thus, IMO, safe to say it's just gunk on the page.

EDIT: not to mention it's in the zone where the contents of the source file would not have produced any marks, meaning it would have to be part of the listing formatting, which is even less likely.

**Comment by XioNYC** [comment]
I just scrutinized the TIFF with a little Photoshop: it's definitely gunk.
