### ISSUE TITLE
Amend pages 1-9 to match "new" format on page 10

### ISSUE THREAD

**Issue by XioNYC** [XioNYC/StarRaiders#8]
There's a tab-stop that hasn't been used before that appears starting on page 10.  Will have to amend all previous pages in order to keep it all consistent.

**Comment by jzatarski** [comment]
I think this whitespace formatting is still wrong? you have a tab before the address, but I think we're pretty sure we're operating on 8 space tabs, right? take for example this line from page 11, using what appears to be your current whitespace model:

```
        A000 00 7F 47   C0      .BYTE   00,$7F,$47,$47,$47,$47,$47,$7F
```

You can check, but the space between the '7' in 47 and 'C' in C0 is 3 spaces. Looking at the scanned pages, and using the title at the top as a ruler, you can count 6 spaces.
currently, I think your model is this?

```
<TAB>AAAA DD DD DD<TAB><rest of code>
```

However, I believe this produces incorrect spacing. I believe, again using the title as a ruler of sorts, that the previous example line should in fact be:

```
     A000 00 7F 47      C0      .BYTE   00,$7F,$47,$47,$47,$47,$47,$7F
```

This is 5 spaces preceding the address. If you assume the title is justified against the left margin, this makes sense. Keep in mind that a printer from the 80's may not have gone all the way to the left edge of the 'printable' region of the paper, so I think this is plausible. This form would look like:

```
<SPx5>AAAA DD DD DD<TAB><rest of code>
```

Also, I think we have decided that in the absence of the data section (D's near the beginning of the line) that those should be filled in by space. I'm not sure what the assembler that atari used produces, but it might make sense they did it that way. This would make the whole prefix of the line a static length section, followed by a single tab, which would make it easier to program the correct spacing (rather than having to detect whether you need two tabs, or one).

**Comment by XioNYC** [comment]
The whitespaces and tab alignments seem to change from page to page and codeblock to codeblock; it suggests multiple coders working on different sections, each with their own coding style(s).

I've agonized on the subject long enough to decide that "however it appears on the page is the right answer".  We can always pretty-print the whole listing once the typing is over.

I've re-amended 000.txt/README accordingly.

**Comment by savetz** [comment]
Curt Vendel just coughed this up today https://www.dropbox.com/s/kem927vs9nea4dx/RAIDERS.TXT?dl=0

If this matches "our" version, it would make getting it into github so much easier.

BUT someone on AtariAge says its lines are truncated. That discussion is here http://atariage.com/forums/topic/243904-star-raiders-source-code-to-be-released/#entry3346217

**Comment by jzatarski** [comment]
yes, both are 'listing' outputs resulting from the assembly of what appears to be two different compilers. It appears star raiders was converted from one assembler to another, as the listings both seem to be the same code, but definitely assembled by a different assembler.

**Comment by XioNYC** [comment]
The truncated dump might be the output from the PDP assmbler; the hardcopy looks more Atari-like.

Maybe "CAMAC" was Atari's cross-assembler (PDP-to-6502)?

ADDENDUM:
The filedump is paginated differently.

**Comment by jzatarski** [comment]
well, the truncated dump from vendel most definitely makes references to CAMAC, which from previous posts on AA was apparently the assembler that ran on the Data General (this is according to curt and former atari employees I believe). I think the one we have was probably converted to whatever the PDP or VAX assembler atari used later was. The Atari OS source I have was, I think most definitely cross compiled, and that shares a very similar syntax to the listing we have from the savetz scan. The comments in that code suggest it was cross compiled from another machine. I don't know if atari was using PDP or VAX at that time, but I think the listing curt posted is probably an earlier one, and the later listing we have was probably after they switched to DEC equipment. I know they have the same version number, but one is likely a later version. I'm guessing atari had the source converted from one syntax to the other at some point, although that's not clear why if the game had already been finished.

**Comment by savetz** [comment]
I think someone at atariage beat us to the finish line? Please see http://atariage.com/forums/topic/243904-star-raiders-source-code-to-be-released/?p=3347394 and message that follows it.
"This builds a bin file identical to the ROM. "
"At this point, all it needs is for someone to look through the code for truncated lines and to restore them from the scanned listing. I'm not going to do that myself."

**Comment by jzatarski** [comment]
they used the listing provided by curt. They are missing some of the comments. I think it is still worthwhile to do (manual) OCR on the listing we have, as it has all of the comments untruncated.

**Comment by savetz** [comment]
Wouldn’t it be faster to use that version as a base then fix truncations/fold in comments? Your call.

**Comment by jzatarski** [comment]
perhaps, but each line would have to be checked and verified carefully, I think. It's really not my call, it's each individual contributors call. You can do it that way if you want, just make sure you stay faithful to the listing we have. The syntax between the two assemblers is different, and would need to be updated to match the listing we have.

**Comment by XioNYC** [comment]
If the goal is to build a binary, all you'd need (quite frankly) is to grep all the bytecodes in order by address, dump that into a hex editor, and _presto!_ you have your BIN.  No assembly required.

Not to badmouth Atari Age but their mantra is "Have you played Atari today?" and not "Have you _preserved_ Atari today?".  Their contributions, quite frankly, appear to be of, by, and for their own circle.  That's fine - it's their prerogative, they're entitled to it like anyone else, and I wish them success [adapting](http://atariage.com/forums/topic/243904-star-raiders-source-code-to-be-released/?p=3347635) the code howso'ere they please.

The point of _this_ project is to preserve the hardcopy that Internet Archive's OCR has failed to do.  It doesn't matter if the typist amends Curt's copy or types it in afresh - it's slow going either way.  Personally, I think it's faster and more accurate to type from scratch rather than amend CAMAC, AAE, or C65.  I also don't appreciate "almost-but-not-quite" version dumps because they are _not_ helping.  (Case in point: the time and energy spent writing this response could have been used instead to get page 21 typed in!)

The **_only**_ thing that will [end program typing agony forever](https://archive.org/stream/1985-01-anticmagazine/Antic_Vol_3-09_1985-01_Utility_Programs#page/n57/mode/2up) is a copy of the **_original source code listing**_ from whence the printout came: line numbers, comments, and intact.  The odds of that are 2^6502:1 against (very roughly, possibly much higher).  So barring a miracle of Fortune, I keep typing.

**Comment by XioNYC** [comment]
Corrigendum:
Make that "page 22", not "page 21" - jzatarski beat me to it :-D

**Comment by savetz** [comment]
You're awesome. Go!
